package main

func getContentType(format string) string {
	var contentType string
	switch format {
	case "html", "htm": contentType = "text/html"
	case "jpg", "jpeg", "jpe": contentType = "image/jpeg"
	case "png": contentType = "image/png"
	case "gif": contentType = "image/gif"
	case "bmp": contentType = "image/bmp"
	case "svg": contentType = "image/svg+xml"
	case "tiff", "tif": contentType = "image/tiff"
	case "ico": contentType = "image/x-icon"
	case "asf", "asx": contentType = "video/x-ms-asf"
	case "wmv": contentType = "video/x-ms-wmv"
	case "wmx": contentType = "video/x-ms-wmx"
	case "wm": contentType = "video/x-ms-wm"
	case "avi": contentType = "video/avi"
	case "divx": contentType = "video/divx"
	case "flv": contentType = "video/x-flv"
	case "mov", "qt": contentType = "video/quicktime"
	case "mpeg", "mpg", "mpe": contentType = "video/mpeg"
	case "mp4", "m4v": contentType = "video/mp4"
	case "ogv": contentType = "video/ogg"
	case "webm": contentType = "video/webm"
	case "mkv": contentType = "video/x-matroska"
	case "3gp", "3gpp": contentType = "video/3gpp"
	case "3g2", "3gp2": contentType = "video/3gpp2"
	case "txt", "asc", "c", "cc", "h", "str": contentType = "text/plain"
	case "csv": contentType = "text/csv"
	case "tsv": contentType = "text/tab-separated-values"
	case "ics": contentType = "text/calendar"
	case "rtx": contentType = "text/richtext"
	case "css": contentType = "text/css"
	case "vtt": contentType = "text/vtt"
	case "woff": contentType = "application/font-woff"
	case "torrent": contentType = "application/x-bittorrent"
	case "xml": contentType = "application/xml"
	case "json": contentType = "application/json"
	case "dfxp": contentType = "application/ttaf+xml"
	case "mp3": contentType = "audio/mpeg"
	case "m4a": contentType = "audio/mp4"
	case "ra", "ram": contentType = "audio/x-realaudio"
	case "wav": contentType = "audio/wav"
	case "ogg", "oga": contentType = "audio/ogg"
	case "mid", "midi": contentType = "audio/midi"
	case "wma": contentType = "audio/x-ms-wma"
	case "wax": contentType = "audio/x-ms-wav"
	case "mka": contentType = "audio/x-matroska"
	case "rtf": contentType = "application/rtf"
	case "js": contentType = "application/javascript"
	case "pdf": contentType = "application/pdf"
	case "swf": contentType = "application/x-shockwave-flash"
	case "class": contentType = "application/java"
	case "tar": contentType = "application/x-tar"
	case "zip": contentType = "application/zip"
	case "gz", "gzip": contentType = "application/x-gzip"
	case "rar": contentType = "application/rar"
	case "7z": contentType = "application/x-7z-compressed"
	case "exe": contentType = "application/x-msdownload"
	case "psd", "xcf": contentType = "application/octet-stream"
	case "doc": contentType = "application/msword"
	case "pot", "pps", "ppt": contentType = "application/vnd.ms-powerpoint"
	case "wri": contentType = "application/vnd.ms-write"
	case "xla", "xls", "xlt", "xlw": contentType = "application/vnd.ms-excel"
	case "mdb": contentType = "application/vnd.ms-access"
	case "mpp": contentType = "application/vnd.ms-project"
	default: contentType = defaultMime
	}

	return contentType
}
